name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: coommetibf inside the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;

            const comment = `🚀 IT CcCcC`;

            github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body: comment
            });
